/*****************************************************************************
**                                                                          **
**                                                                          **
**  DOS Form Designer                                                       **
**  =================                                                       **
**                                                                          **
**  Version 1.00                                                            **
**                                                                          **
**                                                                          **
**  Copyright (C) 1993 Skribby Soft                                         **
**                                                                          **
** ======================================================================== **
**                                                                          **
**  TStaticTitleObjDlg Class                                             	**
**  ------------------------                                                **
**                                                                          **
**  Defined classes:                                                        **
**    - Class TStaticTitleObjDlg                                            **
**                                                                          **
**                                                                          **
**                                                                          **
**  Module Name: TSTOBDLG.CPP                                               **
**                                                                          **
*****************************************************************************/

#include "Compiler.H"

#include "TSTObDlg.H"


void TStaticTitleObjDlg::addTitleLine( int y )
{
	y;
}
