/*----------------------------------------------*/
/*                                  			*/
/*		Boulder Dash 1.0   				    	*/
/*												*/
/*		Figure ID Include File   				*/
/*												*/
/*----------------------------------------------*/

#ifndef ID
#define ID


enum FigureId
{
	idEmpty		= 0,
	idGrass		= 10,

	idMound		= 20,
	idConverter,
	idWall,
	idExit,

	idStone 	= 50,
	idDiamond,

	idSpiral	= 100,
	idButterfly,

	idAmoeba    = 150,

	idPlayer 	= 1000
};

#endif
