/*****************************************************************************
**                                                                          **
**                                                                          **
**  DOS Form Designer                                                       **
**  =================                                                       **
**                                                                          **
**  Version 1.00                                                            **
**                                                                          **
**                                                                          **
**  Copyright (C) 1993 Skribby Soft                                         **
**                                                                          **
** ======================================================================== **
**                                                                          **
**  Help Context Constants                                                  **
**  ----------------------                                                  **
**                                                                          **
**                                                                          **
**                                                                          **
**                                                                          **
**  Module Name: HELPCTX.H                                                  **
**                                                                          **
*****************************************************************************/

const
	hcNoCxt                	= 0,

	hcHelpOnHelp			= 1000,

	hcClose					= 1001,
	hcUndo					= 1002,

	hcMovingObject			= 1020,

	hcAbout					= 1050,

	hcMainFolder			= 1100,

	hcSystemsFolder			= 1111,
	hcSystem				= 1112,

	hcProject				= 1121,
	hcKeyFolder				= 1122,
	hcKey					= 1123,

	hcDialog				= 1131,
	hcSingleField			= 1132,
	hcDoubleField			= 1133,
	hcMCReaderField			= 1134;

