const
  hcDoubleField          = 1133,
  hcFolder               = 1003,
  hcHelpOnHelp           = 1000,
  hcHierarchy            = 1001,
  hcHierarchy2           = 1002,
  hcMainFolder           = 1100,
  hcMovingObject         = 1020,
  hcNoCxt                = 0,
  hcProject              = 1121,
  hcSingleField          = 1132,
  hcSystem               = 1112,
  hcSystemsFolder        = 1111;
