// ****************************
// ***	       Usego	    ***
// ****************************
// ***	File - Conversion   ***
// ****************************


#define SOURCEENTRYLENGTH	    1024
#define DESTINATIONENTRYLENGTH	    256


#define STARTBLOCKLENGTH	    47

#define ENDBLOCKLENGTH		    69
#define ENDBLOCKOFFSET		    948

#define DATAOFFSET		    47

#define DATAENTRYLENGTH 	    9
