/*===========================================================================* 
 *====   KONAS   ============================================================*
 *===========================================================================*
 * Constant.H                                                                *
 *===========================================================================*
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *===========================================================================*/

#ifndef CONSTANT
#define CONSTANT


#define ID_PERSONLIST_BOX       100
#define IDB_NEW_PERSON          110
#define IDB_EDIT_PERSON         111
#define IDB_DELETE_PERSON       112

#define IDB_PRINT_PERSON        120
#define IDB_MC_PERSON           121

#define IDB_PRINT_LIST          130
#define IDB_EXPORT_DATA         131

#define IDB_NEXT_PAGE           201
#define IDB_PREV_PAGE           202

#define IDB_PAGE                300

#define IDB_CLOSE               500
#define IDB_UNDO                501



#endif
/*===================* 
 * End of Constant.H *
 *===================*/