/*----------------------------------------------*/
/*                                  			*/
/*		Boulder Dash 1.0   				    	*/
/*												*/
/*		DiamondExplosive Object Include File   	*/
/*												*/
/*----------------------------------------------*/

#ifndef DIAMEXPL
#define DIAMEXPL

#include "Figures\Explosiv.H"


class DiamondExplosive : public Explosive
{
public:
	virtual void explode();
};

#endif
