/*****************************************************************************
**                                                                          **
**                                                                          **
**  DOS Form Designer                                                       **
**  =================                                                       **
**                                                                          **
**  Version 1.00                                                            **
**                                                                          **
**                                                                          **
**  Copyright (C) 1993 Skribby Soft                                         **
**                                                                          **
** ======================================================================== **
**                                                                          **
**  tvObject Resources                                                      **
**  ------------------                                                      **
**                                                                          **
**                                                                          **
**                                                                          **
**                                                                          **
**  Module Name: TVOBJRES.H                                                 **
**                                                                          **
*****************************************************************************/

#ifndef TVOBJRES
#define TVOBJRES


const
  skOK						=	 1,
  skCancel					=	 2,

  skUndo					=    3,
  skClose					=	 4,

  skUndoShort				=    5,
  skCloseShort				=	 6,
  skCancelShort				=    7,

  skOpen					=	 8,

  skNew						=	 9,
  skDelete					=	10,

  skMove					=	11,

  skTitle					=	12,

  skEndOfListObjTitle		=	13,


  skDeleteConfirmation		=	14,

  skNewObjectDlgTitle		=	15,
  skTypeOfNewObject			=	16;
