/*----------------------------------------------*/
/*                                  			*/
/*		PV 1.0   				    			*/
/*		PV Commands Include File    			*/
/*												*/
/*----------------------------------------------*/


#include <TV.H>


// About Command:
const ushort cmFormDefInit      = 1101;
const ushort cmListLoad         = 1102;
const ushort cmInitDone         = 1108;
const ushort cmAboutDismissed   = 1109;
const ushort cmIntRevision      = 9999;
const ushort cmHeapView			= 1201;


// ListWin Commands:
const ushort cmNewPerson 		= 1500;
const ushort cmEditPerson 		= 1501;
const ushort cmDeletePerson		= 1502;
const ushort cmPrintPerson  	= 1503;
const ushort cmRawPrintPerson	= 1504;
const ushort cmEncodeCard		= 1505;
const ushort cmSaveList		    = 1506;
const ushort cmPrintLog			= 1507;
const ushort cmExportData		= 1508;

// FormDlg Commands:

const ushort cmNextPage			= 1600;
const ushort cmPrevPage			= 1601;
const ushort cmFirstPage		= 1610;
const ushort cmImportOK			= 1650;


// Menu Commands:
const ushort cmMIPrinter		= 2111;