/*----------------------------------------------*/
/*                                  			*/
/*		PV 1.0   				    			*/
/*		PV Help Contexts Include File    		*/
/*												*/
/*----------------------------------------------*/


#include <TV.H>


const ushort hcFormDefInit 		=    2;
const ushort hcEnter			=	 3;

const ushort hcFirstHelp		=   10;
const ushort hcLastHelp			= 1000;

const ushort hcListWin			=  100;
const ushort hcFormDlg			=  150;
const ushort hcFormDlgControl   =  155;


const ushort hcSMOptions	    =  501;
const ushort hcMIPrinter        =  511;