/*----------------------------------------------*/
/*                                  			*/
/*		PV 1.0   				    			*/
/*		PV String List Include File    			*/
/*												*/
/*----------------------------------------------*/


#include <TV.H>


/*----------------------------------------------*/
/*                                  			*/
/*	All the numbers used in StringLists	HAVE	*/
/*	to be SUCCESIVE!                			*/
/*												*/
/*----------------------------------------------*/

const ushort skCorporation      =    1;
const ushort skPerson           =    2;

const ushort skListWindowTitle	=   20;

const ushort skHeapView			=	10;

const ushort skOldDevice 		=	11;
const ushort skFormatedRawPrint	=	12;
const ushort skNumRPCopiesDlg 	=	13;

const ushort skAutoSave			=	14;

const ushort skConfirmNewPerson	=	18;
const ushort skDisableOptions	=	19;

// Form Window
const ushort skFormDlgOK		=	15;
const ushort skFormDlgCancel	=	16;

// List Window
const ushort skPersonList		=    3;
const ushort skNewPerson        =    4;
const ushort skDeletePerson     =    5;
const ushort skEditPerson       =    6;
const ushort skPrintPerson      =    7;
const ushort skRawPrintPerson	=	 8;
const ushort skEncodeCard 		=	 9;
const ushort skPrintLog			=	17;
const ushort skExportData		=	21;
